config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweets
  resources :likes, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :tweet_id }
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.new(like_params)
        
        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end

        redirect_to root_path
    end

    def destroy
        @like = current_user.likes.find(params[:id])
        @like.destroy
        redirect_to root_path
    end

    private

    def like_params
        puts ' '
        puts ' '
        puts params
        puts ' '
        puts ' '

        params.require(:like).permit(:tweet_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def acount_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @tweets = Tweet.all.order("created_at DESC")
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Twitter</h1>
        <% end %>

        <div class="navbar-burger burge" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped to-center">
            <p class="control">
              <%= link_to 'New Tweet', new_tweet_path, class: "button is-info is-inverted" %>
            </p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "button is-info" %>
              </p>
            <% else %>
              <p class="control">
                <%= link_to "Sign In", new_user_session_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>
        <div class="media-content">
            <%= render 'tweets/form' %>
        </div>
    </article>

    <% @tweets.each do | tweet | %>
        <div class="box">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <strong><%= tweet.user.name %></strong><br />
                        <small>@<%= tweet.user.username %></small><br />
                        <p><%= tweet.content %></p>
                    </div>
                    <nav class="level">
                        <div class="level-left is-mobile">
                            <%= link_to tweet, class: "level-item" do %>
                                <span class="icon">🔗</i></span>
                            <% end %>

                            <% if current_user === tweet.user %>
                                <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                                    <span class="icon">✏️</span>
                                <% end %>
                                <%= link_to tweet, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this tweet?" 
                                    } do %>
                                        <span class="icon">🗑</span>
                                <% end %>
                            <% end %>

                            <% like = current_user.likes.find_by(tweet: tweet) %>
                            <% if like.nil? %>
                                <%= button_to "🤍", likes_path, params: { like: {tweet_id: tweet.id }}, method: :post %>
                            <% else %>
                                <%= button_to "❤️", like_path(like), method: :delete %>
                            <% end %>
                            <%= tweet.likes.count %>
                        </div>
                    </nav>
                </div>
            </article>
        </div>
    <% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do | f | %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :content, as: :text, label: "Tweet about it", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweet..." %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Content:</strong>
    <%= tweet.content %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'feed' %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>